service: sls-notes-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  stage: prod
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    NOTES_TABLE: ${self:service}-${opt:stage, self:provider.stage} # if stage name is passed as param, use that to name the table, else use 'prod'

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain # Dont delete table when we remove the stack
      Properties:
        TableName: ${self:provider.environment.NOTES_TABLE}
